### ISSUE TITLE
Class Lubusin\Mojo\MojoServiceProvider not found !!

### ISSUE THREAD

**Issue by psnilesh** [lubusIN/laravel-mojo#1]
`**Writing lock file**
**Generating optimized autoload files**
 post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
 post-autoload-dump: @php artisan package:discover
Executing command (CWD): '_/usr/bin/php7.1' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='-1' artisan package:discover_

**In ProviderRepository.php line 208:
                                                  
  Class 'Lubusin\Mojo\ServiceProvider' not found**  
                                                  

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
`

I get the above error when trying to install this package. Can't complete the migration because of the same error,  class MojoServiceProvider not found.

**Comment by kashif06** [comment]
Class 'Lubusin\Mojo\ServiceProvider' not found. Not able to run migration.After adding in config.app within providers array.

**Comment by ajitbohra** [comment]
@NileshPS thanks for the #2 👍 

@kashif06 try installing now

**Comment by kashif06** [comment]
I am trying to install but it's showing the same error and its composer is installing v2.0.3

**Comment by kashif06** [comment]
It's Working Now.Thanks !!!

**Comment by ajitbohra** [comment]
super looking forward to your feedback / suggestion :)

**Comment by kashif06** [comment]
In the documentation there is a post request to the webhook controller as it will get saved in the database only via webhook. So the post request Route::post('instamojo/webhook). How will it get this post request.Or it is something we have to provide manually.

**Comment by introwit** [comment]
@kashif06 Webhook is the URL to which instamojo send's the payment details as a POST request. Suppose your site is `example.com`, since we have defined a route `example.com/instamojo/webhook` to accept a POST request and we have let instamojo know that this is the route you have to post to via the [config file](https://github.com/lubusIN/laravel-mojo/blob/master/src/config/laravelmojo.php#L43-L50), instamojo is like 'ok I will send a POST request' to that url. More in the [docs](https://github.com/lubusIN/laravel-mojo/wiki/3.-Webhook) , also it won't work for local sites as written in the `NOTES` section on that documentation page 🙂

**Comment by kashif06** [comment]
So I just have to put Route::post( 'quiz.site/instamojo/webhook', \Lubusin\Mojo\Controllers\WebhookController@handleWebhook');

Where quiz.site is my url(suppose live url) so it handle automatically everything.

**Comment by kashif06** [comment]
I think I got it what you are trying to say. In my env file I just have to put the INSTAMOJO_WEBHOOK_URL=quiz.site/instamojo/webhook and this will handle everything. RIGHT??

**Comment by introwit** [comment]
@kashif06 you don't have to prefix `quiz.site`, in your `.env` file add INSTAMOJO_WEBHOOK_URL=instamojo/webhook after that follow the steps [here](https://github.com/lubusIN/laravel-mojo/wiki/3.-Webhook)

**Comment by kashif06** [comment]
Thanks for the information. I will try on live server and let you know.If it works I would recommend every friend of mine to use this.!!!

**Comment by sunnyexchange4media** [comment]
> orward to your feedback / suggestion :)

What you did please hjelp
