### ISSUE TITLE
Class 'Lubusin\Mojo\ServiceProvider' not found

### ISSUE THREAD

**Issue by kashif06** [lubusIN/laravel-mojo#3]
Class 'Lubusin\Mojo\ServiceProvider' not found.After adding in config/providers array.

**Comment by ajitbohra** [comment]
@kashif06 2.0.4 release fixes this let us know if you still face the issue

**Comment by kashif06** [comment]
How can I install v2.0.4. I am trying to install but it is installing v2.0.3

**Comment by introwit** [comment]
@kashif06 try now, it will install 2.0.4 :) @ajitbohra after tagging a release we need to go to packagist & click on the `update` button to allow packagist to see the new release immediately.

**Comment by ajitbohra** [comment]
@introwit my bad thanks for the heads up 👍
